name: ai-content-gen
version: 0.1.0
description: Generates SEO-friendly product titles using the DeepSeek API.
author: [Your Name/Organization]
license: MIT
jsonschema:
  type: object
  properties:
    ai_provider:
      type: string
      description: The AI provider to use for content generation.
      enum: ["deepseek", "openai"]
      default: "deepseek"
    deepseek_api_key:
      type: string
      description: Your API key for the DeepSeek API. (Required if ai_provider is 'deepseek')
    deepseek_model_name:
      type: string
      description: The DeepSeek model to use (e.g., 'deepseek-coder', 'deepseek-chat').
      default: 'deepseek-chat'
    openai_api_key:
      type: string
      description: Your API key for the OpenAI API. (Required if ai_provider is 'openai')
    openai_model_name:
      type: string
      description: The OpenAI model to use (e.g., 'gpt-4o', 'gpt-3.5-turbo').
      default: 'gpt-4o'
    default_prompt_template_path:
      type: string
      description: Path to a custom prompt template file (optional).
  required:
    - ai_provider
    # deepseek_api_key is conditionally required
    # openai_api_key is conditionally required 